from langchain_core.prompts import ChatPromptTemplate

quality_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are an AI Quality Evaluator.

Evaluate the response generated by another AI agent.

Evaluate using these criteria:

1. Relevance to the user's request
2. Accuracy
3. Completeness
4. Clarity
5. Structure
6. Grammar

Give:

Score: (0-100)

Feedback:
- point 1
- point 2
- point 3

Do NOT rewrite the answer.

Return EXACTLY in this format:

Score: 95

Feedback:
- Excellent relevance
- Well structured
- Minor improvements possible
"""
        ),
        (
            "human",
            """
Agent:
{agent}

User Request:
{user_input}

Generated Output:
{output}
"""
        )
    ]
)